### ISSUE TITLE
Unable to locate package nvidia-graphics-drivers-555

### ISSUE THREAD

**Issue by ClaireRupikaRamode** [oddmario/NVIDIA-Ubuntu-Driver-Guide#5]
After following all the steps when i try to run "sudo apt install nvidia-driver-555" i receive this error:

E: Unable to locate package nvidia-graphics-drivers-555

Should i stay with 550, try 560 or wait?

**Comment by oddmario** [comment]
Hello,

I have just tried to reproduce the issue but I was able to install the nvidia-driver-555 package here.

Were you able to run `sudo add-apt-repository ppa:graphics-drivers/ppa` without any errors? Did you make sure to run `sudo apt update` after adding the repository?

**Comment by ClaireRupikaRamode** [comment]
Hi, yes "sudo add-apt-repository ppa:graphics-drivers/ppa" was completed without any errors and i also did the "sudo apt update" but for some reason the repo added every single driver (even 550 and 560) except for 555.

**Comment by ClaireRupikaRamode** [comment]
Even if i look into the overview of published packages in "https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa" it seems that 555 is not available, only 550 and 560.

![Screenshot_20241214_074437_Firefox](https://github.com/user-attachments/assets/43f98790-9be9-41ba-87ff-c01964750357)

**Comment by oddmario** [comment]
I see i see, you are right actually. I might have had the package cached on my side.

In this case version `nvidia-graphics-drivers-560` should be the one to install. 

I will update the guide accordingly

**Comment by ClaireRupikaRamode** [comment]
Ok, i'll try 560 then.
Thx!

**Comment by oddmario** [comment]
you're very welcome! :)
